# Generated by Django 5.0.2 on 2024-07-24 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_ov_name_project_sap_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_name',
            field=models.CharField(max_length=100, verbose_name='Nombre de Contratista'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_ruc',
            field=models.CharField(max_length=20, verbose_name='RUC del Contratista'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.client', verbose_name='Clientes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contractor', verbose_name='Contratista'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ov_name',
            field=models.CharField(max_length=100, verbose_name='Orden de Venta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del projecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sap_code',
            field=models.CharField(max_length=50, verbose_name='Código SAP'),
        ),
    ]
