# Generated by Django 5.0.2 on 2024-07-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_client_client_name_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='client',
            name='client_ruc',
            field=models.CharField(default='', max_length=50, verbose_name='Ruc del cliente'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(default='', max_length=50, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
