# Generated by Django 5.0.2 on 2024-07-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alimentos_consumibles_epps_equipos_herramientas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='consumibles',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='epps',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='manodeobra',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='misc',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='codigo_barras',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='en_stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='fabricante',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='num_articulo',
            field=models.CharField(max_length=50, verbose_name='Número de Articulo'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='precio_unitario_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario Diario'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='ultimo_precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ultimo Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Unidad de Medida'),
        ),
    ]
