# Generated by Django 5.0.2 on 2024-07-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='real_price',
            field=models.FloatField(default=0),
        ),
    ]
