# Generated by Django 5.0.2 on 2024-08-09 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budgetitem_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='facturacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='budget',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='budget',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='budget',
            name='no_incluye',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='tiempo_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='tiempo_garantia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='tiempo_servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='valor_total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
