# Generated by Django 5.0.2 on 2024-08-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_facturacion_budget_fecha_budget_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='real_price_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='unidad_medida',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
