# Generated by Django 5.0.2 on 2024-08-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_budgetitem_vida_util'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='precio_item_proyecto',
            field=models.FloatField(default=0),
        ),
    ]
