# Generated by Django 5.0.2 on 2024-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_remove_budget_valor_total_budget_valor_total_soles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='valor_total_usd',
            new_name='total_dolares_final',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='valor_total_soles',
            new_name='total_soles_final',
        ),
        migrations.AddField(
            model_name='budget',
            name='gastos_administrativos',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_dolares_parcial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_soles_parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
