# Generated by Django 5.0.2 on 2024-08-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_rename_valor_total_usd_budget_total_dolares_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_gastos_administrativos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_utilidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_dolares_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_dolares_parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
