# Generated by Django 5.0.2 on 2024-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_budget_total_gastos_administrativos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
