# Generated by Django 5.0.2 on 2024-08-17 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_budget_budget_name'),
        ('projects', '0007_remove_project_sap_code_alter_project_ov_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='', max_length=100, verbose_name='Presupuesto - Cotización'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project', verbose_name='Proyecto'),
        ),
    ]
