# Generated by Django 5.0.2 on 2024-08-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Documento'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_record', models.FileField(upload_to='station_attendance/')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tareo del Día')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='station.station', verbose_name='Estación')),
            ],
        ),
    ]
