# Generated by Django 5.0.3 on 2024-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='resources',
        ),
    ]
