# Generated by Django 5.0.3 on 2024-07-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_tasks_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='object',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='orden_venta',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='verb',
            field=models.CharField(default='', max_length=100),
        ),
    ]
