# Generated by Django 5.0.3 on 2024-07-21 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_tasks_object_alter_tasks_orden_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsTasksOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cards')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.tasks')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
