# Generated by Django 5.0.3 on 2024-07-21 03:59
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardstasksorder'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='cards',
        ),
        migrations.AddField(
            model_name='tasks',
            name='cards',
            field=models.ManyToManyField(related_name='cards', through='cards.CardsTasksOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]

        