# Generated by Django 5.0.3 on 2024-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_tasks_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='total_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cards',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='cards',
            field=models.ManyToManyField(related_name='tasks', through='cards.CardsTasksOrder', to='cards.cards'),
        ),
    ]
