# Generated by Django 5.0.3 on 2024-07-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_cardstasksorder_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='valuation',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
