# Generated by Django 5.0.3 on 2024-05-14 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('calidad', 'Calidad'), ('seguridad', 'Seguridad')], default='calidad', max_length=10, verbose_name='Tipo de Recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measures', models.CharField(max_length=100)),
                ('hazard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='resources.hazard')),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('hazard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='resources.hazard')),
            ],
        ),
        migrations.AddField(
            model_name='hazard',
            name='resources',
            field=models.ManyToManyField(related_name='hazards', to='resources.resource'),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('hazard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='resources.hazard')),
            ],
        ),
    ]
